/**
 * Regenerate `e2e/fixtures/inputlog-round1.json`.
 *
 *   pnpm --filter @rematch/web gen:inputlog
 *
 * The fixture is a full Round 1 played by the engine's scripted mid-range player (the
 * same stand-in its determinism tests and bench use), recorded as an input log, plus
 * the final state hash computed in Node. The e2e suite feeds that log to the browser
 * and asserts the browser reaches the same hash — spec AC 3.
 *
 * Everything about the recording is derived from two integers: the session seed (which
 * yields the round seed through `roundSeed`, so the e2e can reach the same round seed
 * from `?seed=`) and the player seed (which drives the scripted player's coin flips).
 * Regenerate whenever `src/strategies/round1.js` or an engine rule changes — the
 * fixture's regression test in `pnpm verify` will tell you when that has happened.
 */
import { writeFileSync } from 'node:fs';
import type { InputLog, GameState } from '@rematch/engine';
import { createSandbox } from '@rematch/sandbox';

import { deterministicClock } from '../src/game/clock.ts';
import { roundSeed } from '../src/game/seeds.ts';
import { quantizeLog, readStrategySource, replayInNode } from './replay-node.ts';

/** Fixed so the fixture is reproducible; the e2e passes this as `?seed=`. */
const SESSION_SEED = 424242;
const ROUND = 1;
/** Independent seed for the scripted player, so the match and the player decorrelate. */
const PLAYER_SEED = 90210;
const STRATEGY = 'round1';

const OUT = new URL('../e2e/fixtures/inputlog-round1.json', import.meta.url);

/**
 * The engine's scripted pseudo-player lives in its test helpers, which are not part of
 * the package's public surface. Loaded through a runtime-computed specifier — the same
 * trick `engine/test/fixtures.ts` uses to reach into `contract` — so TypeScript types
 * it as `any` and never resolves a declaration file across the package boundary.
 */
type EngineHelpers = {
  playMatch: (
    seed: number,
    runner: unknown,
    playerSeed: number,
    maxTicks?: number,
  ) => { final: GameState; log: InputLog };
};

async function loadEngineHelpers(): Promise<EngineHelpers> {
  const href = new URL('../../engine/test/helpers.ts', import.meta.url).href;
  const mod: unknown = await import(href);
  return mod as EngineHelpers;
}

async function main(): Promise<void> {
  const seed = roundSeed(SESSION_SEED, ROUND);
  const source = readStrategySource(STRATEGY);

  // 1. Play a match with the scripted player and record its inputs.
  const helpers = await loadEngineHelpers();
  const sandbox = await createSandbox();
  const runner = sandbox.load(source, { now: deterministicClock() });
  const played = helpers.playMatch(seed, runner, PLAYER_SEED);
  runner.dispose();

  // 2. Round the recorded floats, then take the hash of the log **as written**.
  const log = quantizeLog(played.log);
  const result = await replayInNode(seed, log, source);

  const fixture = {
    note: 'Generated by scripts/gen-inputlog.ts. Do not edit by hand.',
    sessionSeed: SESSION_SEED,
    round: ROUND,
    seed,
    playerSeed: PLAYER_SEED,
    strategy: STRATEGY,
    ticks: result.ticks,
    outcome: result.outcome,
    /** Final-state hash from Node. The browser must reproduce this exactly (AC 3). */
    hash: result.hash,
    log,
  };

  // Hand-rolled formatting: the header stays readable and each tick is one line, so
  // the diff of a regenerated fixture shows which ticks changed instead of one blob.
  const header = JSON.stringify({ ...fixture, log: [] }, null, 2).replace(/,\n\s*"log": \[\]\n\}$/, '');
  const lines = log.map((input) => `  ${JSON.stringify(input)}`).join(',\n');
  writeFileSync(OUT, `${header},\n "log": [\n${lines}\n ]\n}\n`, 'utf8');

  console.log(`session seed : ${SESSION_SEED}`);
  console.log(`round seed   : ${seed}`);
  console.log(`strategy     : ${STRATEGY} (${source.length} bytes)`);
  console.log(`ticks        : ${result.ticks} (${(result.ticks / 60).toFixed(2)}s), recorded ${played.log.length}`);
  console.log(`outcome      : ${result.outcome}`);
  console.log(`node hash    : ${result.hash}`);
  console.log(`written      : ${OUT.pathname}`);
}

await main();
